server:
 servlet:
    context-path: /livros/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://AndersonM:swdevcqi@cluster0.squbxys.mongodb.net/learn-all?retryWrites=true&w=majority}
      auto-index-creation: true        
springdoc:
  swagger-ui:
    path: /public/swagger


